#===============================================================================
# Copyright 2021 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

variables:
  DESCRIPTION: ReleaseTesting

jobs:
- job: TestPyPi
  strategy:
    matrix:
      ubuntu - python38:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
        conda.activate: 'conda activate'
      ubuntu - python37:
        imageName: 'ubuntu-latest'
        python.version: '3.7'
        conda.activate: 'conda activate'
      ubuntu - python36:
        imageName: 'ubuntu-latest'
        python.version: '3.6'
        conda.activate: 'conda activate'
      mac - python38:
        imageName: 'macos-latest'
        python.version: '3.8'
        conda.activate: 'source activate'
      mac - python37:
        imageName: 'macos-latest'
        python.version: '3.7'
        conda.activate: 'source activate'
      mac - python36:
        imageName: 'macos-latest'
        python.version: '3.6'
        conda.activate: 'source activate'
      windows - python38:
        imageName: 'windows-latest'
        python.version: '3.8'
        conda.activate: 'call activate'
      windows - python37:
        imageName: 'windows-latest'
        python.version: '3.7'
        conda.activate: 'call activate'
      windows - python36:
        imageName: 'windows-latest'
        python.version: '3.6'
        conda.activate: 'call activate'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Add conda to PATH
  - script: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    condition: eq( variables['Agent.OS'], 'Darwin')
    displayName: Add sudo access
  - script: |
      conda update -y -q conda
      conda create -y -q -n CB python=$(python.version) scikit-learn-intelex pandas pytest
    displayName: 'Install scikit-learn-intelex'
  - script: |
# . /usr/share/miniconda/etc/profile.d/conda.sh
      $(conda.activate) CB
      cd ..
      python -c "import sklearnex"
    displayName: 'Testing of import'
#   - script: |
#       call activate CB
#       pytest --pyargs sklearnex
#     displayName: 'Testing of scikit-learn-intelex'
