{% set version = '0.2019.2' %}
{% set buildnumber = 1 %}

package:
    name: daal4py
    version: {{version}}

source:
    path: ..
    #git_url: https://github.com/IntelPython/daal4py.git

requirements:
    build:
        - python
        - setuptools
        - numpy-devel >=1.15
        - tbb-devel
        - daal-devel >=2019.0
        - cython
        - jinja2
        - mpich                  # [not win]
        - impi-devel             # [win]
    run:
        - python
        - tbb
        - daal >=2019.0
        - mpich                  # [not win]
        - impi_rt                # [win]
    test:
        - pandas
        - scipy

build:
    number: {{buildnumber}}
    include_recipe: False

test:
    requires:
        - pandas
        - scipy
    imports:
        - daal4py
    source_files:
        - examples
        - tests

about:
    license: Apache 2.0
    license_file: LICENSE
