{% set version = '0.2020.0' %}
{% set buildnumber = 0 %}

package:
    name: daal4py
    version: {{version}}

source:
    path: ..

build:
    number: {{buildnumber}}
    include_recipe: False
    script_env:
     - DPCPP_VAR
     - DAALROOT
    ignore_run_exports:
       - python

requirements:
    host:
        - python
        - setuptools
        - numpy >=1.15
        - daal-devel >=2019.0
        - cython
        - jinja2
        - impi-devel
        - clang-tools
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
    run:
        - python
        - daal >=2019.0
        - {{ pin_compatible('numpy') }}

test:
    requires:
        - pandas
        - scipy
        - scikit-learn
        - impi_rt
    imports:
        - daal4py
    source_files:
        - examples
        - tests
    commands:
        - mpirun -n 4 python -m unittest discover -v -s tests -p spmd*.py # [not win]
        - mpiexec -localonly -n 4 python -m unittest discover -v -s tests -p spmd*.py # [win]
        - python -m unittest discover -v -s tests -p test*.py
        - cd examples && python run_examples.py

about:
    home: https://intelpython.github.io/daal4py/
    license: Apache 2.0
    license_file: LICENSE
    summary: A convenient Python API to Intel (R) DAAL
