{% set version = '0.2019.5' %}
{% set buildnumber = 0 %}

package:
    name: daal4py
    version: {{version}}

source:
    path: ..
    #git_url: https://github.com/IntelPython/daal4py.git

build:
    number: {{buildnumber}}
    include_recipe: False

requirements:
    host:
        - python
        - setuptools
        - numpy >=1.15
        - tbb-devel
        - daal-devel >=2019.0
        - cython
        - jinja2
        - mpich                  # [not win]
        - impi-devel             # [win]
    run:
        - python
        - tbb
        - daal >=2019.0
        - {{ pin_compatible('numpy') }}

test:
    requires:
        - pandas
        - scipy
        - scikit-learn
        - mpich                  # [not win]
        - impi_rt                # [win]
    imports:
        - daal4py
    source_files:
        - examples
        - tests
    commands:
        - mpirun -n 4 python -m unittest discover -v -s tests -p spmd*.py # [not win]
        - mpiexec -localonly -n 4 python -m unittest discover -v -s tests -p spmd*.py # [win]
        - python -m unittest discover -v -s tests -p test*.py
        - cd examples && python run_examples.py && cd ..

about:
    home: https://intelpython.github.io/daal4py/
    license: Apache 2.0
    license_file: LICENSE
    summary: A convenient Python API to Intel (R) DAAL
