name: oneDAL nightly build

on:
  schedule:
    - cron: '0 21 * * *'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_lnx:
    name: build Linux
    if: github.repository == 'icfaust/scikit-learn-intelex'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
        with:
          repository: oneapi-src/oneDAL
      - name: Install DPC++
        run: .ci/env/apt.sh dpcpp
      - name: System Info
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/describe_system.sh
      - name: Make daal
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/build.sh --compiler icx  --optimizations avx2 --target daal
      - name: Make onedal
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/build.sh --compiler icx  --optimizations avx2 --target onedal
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: __release_lnx
          path: ./__release_lnx_icx

  build_win:
    name: build Windows
    if: github.repository == 'icfaust/scikit-learn-intelex'
    runs-on: windows-2022

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
        with:
          repository: oneapi-src/oneDAL
      - name: Install DPC++
        run: |
          $env:PATH="C:\msys64\usr\bin;$env:PATH"
          echo $env:PATH=C:\msys64\usr\bin;$env:PATH >> $env.GITHUB_ENV
          pip install cpufeature
          pacman -S -y --noconfirm zip dos2unix tree wget gcc
          echo "Download intel DPC++ compiler"
          wget -q -O dpcpp_installer.exe https://registrationcenter-download.intel.com/akdlm/IRC_NAS/7991e201-ca0f-4689-bdb6-1ed73a8246fd/w_dpcpp-cpp-compiler_p_2024.2.0.491_offline.exe
          echo "Unpacking DPC++ installer"
          Start-Process ".\dpcpp_installer.exe" -ArgumentList "--s --x --f oneAPI" -Wait
          echo "Installing DPC++ compiler"
          Start-Process ".\oneAPI\bootstrapper.exe" -ArgumentList "-s --eula=accept --install-dir=dpcpp" -Wait
          # This can take 20 minutes...
          echo "DPC++ install complete"
      - name: System Info
        run: |
          echo "source dpcpp"
          cmd.exe "/K" '".\dpcpp\compiler\latest\env\vars.bat" && powershell'
          Get-Variable -Scope script
          bash .ci/scripts/describe_system.sh
      - name: Make daal
        shell: cmd
        run: |
          # call .\dpcpp\compiler\latest\env\vars.bat
          call .\.ci\scripts\build.bat daal vc avx2
      - name: Make onedal
        shell: cmd
        run: |
          # call .\dpcpp\compiler\latest\env\vars.bat
          call .\.ci\scripts\build.bat onedal_c vc avx2
      - name: Make oneapi_dpc
        shell: cmd
        run: |
          call .\dpcpp\compiler\latest\env\vars.bat
          call .\.ci\scripts\build.bat onedal_dpc vc avx2
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: __release_win
          path: .\__release_win
